# Generated by Django 3.0.8 on 2020-08-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='No Ingredients'),
        ),
    ]
