# Generated by Django 3.0.8 on 2020-08-23 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_auto_20200822_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recipes',
            field=models.ManyToManyField(blank=True, to='cookbook.Recipe'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.IntegerField()),
                ('like', models.ManyToManyField(blank=True, related_name='user_like', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='comments',
            field=models.ManyToManyField(blank=True, to='cookbook.Comment'),
        ),
    ]
