# Generated by Django 3.0.8 on 2020-08-23 04:37

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('cookbook', '0005_auto_20200823_0034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Review',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='comments',
            new_name='reviews',
        ),
    ]
