# Generated by Django 3.0.8 on 2020-08-23 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0006_auto_20200823_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='user_recipe', to='cookbook.Recipe'),
        ),
    ]
