# Generated by Django 3.0.8 on 2020-08-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0007_auto_20200823_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='recipes',
            field=models.ManyToManyField(blank=True, to='cookbook.Recipe'),
        ),
    ]
