# Generated by Django 3.0.8 on 2020-08-25 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0009_auto_20200824_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
