# Generated by Django 3.0.8 on 2020-08-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0010_recipe_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='No user description'),
        ),
    ]
