# Generated by Django 3.0.8 on 2020-08-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0011_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
